app = "eers-chatbot"

primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8501"

[[services]]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024"
  cpu_kind = "shared"

# 자동 중지 방지
[[restart]]
  policy = "always"
  retries = 2
